
language: r
warnings_are_errors: false
sudo: required
cache: packages


before_install:

  - sudo apt-get -qq update
  - sudo apt-get install libgmp3-dev


install:
  - Rscript -e "install.packages(c( 'devtools', 'roxygen2', 'testthat', 'knitr', 'rmarkdown', 'Rcpp', 'RcppArmadillo', 'shiny', 'jpeg', 'png', 'OpenImageR', 'ClusterR', 'tiff', 'covr'), repos =  'https://cloud.r-project.org/' )"


after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'


notifications:
  email:
    on_success: change
    on_failure: change
